version: 2
workflows:
  version: 2
  default:
    jobs:
      - "python-3.7"

jobs:
  "python-3.7":
    docker:
      - image: continuumio/miniconda:latest

    steps:
      - checkout 

      - run:
          name: Install Cookiecutter
          command: |
            pip install cookiecutter --user
            cookiecutter --help