name: CI

on:
  push:
    branches: "*"
  pull_request:
    branches: master


jobs:

  build:
    name: cookiecutter-template
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Cookiecutter
        run: |
          sudo apt-get install -y tree
          python -m pip install cookiecutter pytest
      - name: Test Template Rendering
        run: |
          cookiecutter . --no-input
          cd ./python_boilerplate && tree -L 3
          python -m pip install -e .
          pytest -v
